# Generated by Django 4.0 on 2022-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=150),
        ),
    ]
